### PR TITLE
Fix error[E0635]: unknown feature `stdsimd` 

### PR DESCRIPTION
**Pull request by glenfletcher**
I received the following error when trying to build on `Linux 6.6.10-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jan  5 17:38:36 UTC 2024 x86_64 GNU/Linux`:
```
error[E0635]: unknown feature `stdsimd`
  --> /home/glen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.3/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: Recipe `build` failed on line 4 with exit code 101
```
After searching for this error, I found the following:
aHash issues: tkaitchuck/aHash#195 and tkaitchuck/aHash#200
rust-lang issues: https://users.rust-lang.org/t/error-e0635-unknown-feature-stdsimd/106445

Based on these, I used `cargo tree -i ahash@0.7.6` to get the following:
```
ahash v0.7.6
├── hashbrown v0.11.2
│   └── lasso v0.5.1
│       └── grass v0.11.2
│           [build-dependencies]
│           └── celeste v0.8.1 (/home/glen/code/celeste)
├── sqlx-core v0.6.3
│   └── sqlx-macros v0.6.3 (proc-macro)
│       └── sqlx v0.6.3
│           ├── sea-orm v0.10.7
│           │   ├── celeste v0.8.1 (/home/glen/code/celeste)
│           │   └── sea-orm-migration v0.10.7
│           │       └── celeste v0.8.1 (/home/glen/code/celeste)
│           └── sea-query-binder v0.2.2
│               └── sea-orm v0.10.7 (*)
└── sqlx-core v0.6.3
    └── sqlx v0.6.3 (*)
```

Based on this, I updated the version of the `grass` and `sea-orm` dependencies and deleted `Cargo.lock` so it could be regenerated; this fixed the build error on my system.

### CODE REVIEW

**Comment by hwittenborn** [comment]
I'm terribly sorry for the delay on this @glenfletcher. I must've overlooked this somehow, and I'm not quite sure how that happened :(

Sadly with the amount of changes made in `Cargo.lock`, it makes it a bit hard for me to audit that everything looks fine. I likewise ended up making this change myself, though I did [credit you for such](https://github.com/hwittenborn/celeste/commit/5787c2538036812943c08fff11a1d6a1f2a9a992) in the repository.

Sorry that this PR couldn't be merged, and even more so that it took this long to get to. Hopefully this doesn't happen again in the future; I'll send a message out if I become busy to the point where this would happen.

**Comment by yochananmarqos** [comment]
@hwittenborn By the way, I applied this PR three months ago in the AUR package. I'll update to 0.8.2 shortly.

**Comment by hwittenborn** [comment]
You're all good @yochananmarqos, I would've done the same as well if something causing failed builds hadn't been fixed in a while. Thanks for the info though, it's appreciated :muscle:
